## Индивидуальное задание
Дана целочисленная прямоугольная матрица. Определить количество столбцов, не содержащих ни одного нулевого элемента. Характеристикой строки целочисленной матрицы назовем сумму ее положительных четных элементов. Переставляя строки заданной матрицы, расположить их в соответствии с ростом характеристик.

In [11]:
import numpy as np

m = int(input("Введите размерность матрицы:\nm = "))
n = int(input("n = "))
matrix =  np.random.randint(-10, 20, size=(m, n))

Введите размерность матрицы:
m = 5
n = 3


In [12]:
print("Матрица:\n", matrix)

Матрица:
 [[-3 -4  3]
 [-1  5  8]
 [-3 -7 -5]
 [-4 -6 -7]
 [ 5  8 16]]


In [14]:

non_zero_columns = np.count_nonzero(np.prod(matrix, axis=0))
print("Количество столбцов без нулевых элементов:", non_zero_columns)

row_characteristics = np.sum(matrix * (matrix > 0) * (matrix % 2 == 0), axis=1)

sorted_indices = np.argsort(row_characteristics)

sorted_matrix = matrix[sorted_indices]
print("Отсортированная матрица:")
print(sorted_matrix)


Количество столбцов без нулевых элементов: 3
Отсортированная матрица:
[[-3 -4  3]
 [-3 -7 -5]
 [-4 -6 -7]
 [-1  5  8]
 [ 5  8 16]]
